# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import decimal


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1026, 262)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(110, 61, 113, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 61, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(560, 61, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(410, 61, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 111, 113, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(260, 111, 113, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(560, 111, 113, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(410, 111, 113, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(860, 61, 113, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(710, 61, 113, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(860, 111, 113, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(710, 111, 113, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(470, 170, 131, 61))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 21, 91, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 61, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 111, 81, 16))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(90, 50, 20, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(100, 42, 881, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(100, 141, 881, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(970, 50, 20, 101))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(310, 190, 113, 22))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(170, 190, 131, 16))
        self.label_4.setObjectName("label_4")

        self.lineEdit.setText("1")
        self.lineEdit_13.setText("1")

        self.lineEdit.textChanged[str].connect(self.onChanged2)
        self.lineEdit_13.textChanged[str].connect(self.onChanged)
        self.pushButton.clicked.connect(self.reset)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def reset(self):
        self.lineEdit.setText("")
        self.lineEdit_5.setText("")  # Keyfi
        self.lineEdit_6.setText("")  # 10
        self.lineEdit_8.setText("")  # 15
        self.lineEdit_7.setText("")  # 20
        self.lineEdit_11.setText("")  # 30
        self.lineEdit_12.setText("")  # 25

    def onChanged2(self):
        try:
            self.keyfi = self.lineEdit.text()

            self.lineEdit_5.setText(
                "{:.3f}".format(
                    (float(self.keyfi) / 100 + 1) * (float(self.lineEdit_13.text()))
                )
            )
        except:
            self.lineEdit_5.setText("Hata Oluştu...")

    def onChanged(self):
        self.keyfi = self.lineEdit.text()

        self.lineEdit_5.setText(
            "{:.3f}".format(
                (float(self.keyfi) / 100 + 1) * (float(self.lineEdit_13.text()))
            )
        )  # Keyfi

        try:
            self.lineEdit_6.setText(
                "{:.3f}".format((int(10) / 100 + 1) * (float(self.lineEdit_13.text())))
            )  # 10
        except:
            x = ""
        try:
            self.lineEdit_8.setText(
                "{:.3f}".format((int(15) / 100 + 1) * (float(self.lineEdit_13.text())))
            )  # 15
        except:
            x = ""
        try:
            self.lineEdit_7.setText(
                "{:.3f}".format((int(20) / 100 + 1) * (float(self.lineEdit_13.text())))
            )  # 20
        except:
            x = ""
        try:
            self.lineEdit_12.setText(
                "{:.3f}".format((int(25) / 100 + 1) * (float(self.lineEdit_13.text())))
            )  # 25
        except:
            x = ""
        try:
            self.lineEdit_11.setText(
                "{:.3f}".format((int(30) / 100 + 1) * (float(self.lineEdit_13.text())))
            )  # 30
        except:
            x = ""

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_2.setText(_translate("Form", "%10"))
        self.lineEdit_3.setText(_translate("Form", "%20"))
        self.lineEdit_4.setText(_translate("Form", "%15"))
        self.lineEdit_9.setText(_translate("Form", "%30"))
        self.lineEdit_10.setText(_translate("Form", "%25"))
        self.pushButton.setText(_translate("Form", "Sıfırla"))
        self.label.setText(_translate("Form", "Keyfi Yüzde"))
        self.label_2.setText(_translate("Form", "Yüzdeler"))
        self.label_3.setText(_translate("Form", "Yüzdeli Fiyat"))
        self.label_4.setText(_translate("Form", "İşlem Yapılacak Fiyat"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
